require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
